### ISSUE TITLE
Add quizzes to course spec

### ISSUE THREAD

**Issue by skyclo** [ideoxan/www#66]
Add quizzes to the course specification. The following format is proposed:
```yaml
name: <string>
description: <string>

environment:
  type: "quiz" # required for quizzes

questions:
  - title: <string>
    content: <string> # possible support for markdown?
    type: <string: "multiple_choice"|"fill_in"|"dropdown">
    scramble: <boolean> # only if type is of "multiple_choice"|"dropdown"
    options: # only if type is of "multiple_choice"|"dropdown"
      - value: <string> # value of election
        correct: <boolean> # multiple correct answers are only possible with multiple choice
    # if fill_in is used, we should add more configuration options below (ex. ignore case, etc).
```

This will allow for a dynamic course specification for quizzes that can support multiple question/election styles.
